- .gitignore
- README.md
- harness-delegate-ng/.helmignore
- harness-delegate-ng/Chart.yaml
- harness-delegate-ng/README.md
- harness-delegate-ng/templates/_helpers.tpl
- harness-delegate-ng/templates/cluster-rolebinding.yaml
- harness-delegate-ng/templates/configMap.yaml
- harness-delegate-ng/templates/deployment.yaml
- harness-delegate-ng/templates/hpa.yaml
- harness-delegate-ng/templates/proxy/proxyConfigMap.yaml
- harness-delegate-ng/templates/proxy/proxySecret.yaml
- harness-delegate-ng/templates/role.yaml
- harness-delegate-ng/templates/roleBinding.yaml
- harness-delegate-ng/templates/secret.yaml
- harness-delegate-ng/templates/service.yaml
- harness-delegate-ng/templates/serviceaccount.yaml
- harness-delegate-ng/templates/upgrader/upgraderConfigMap.yaml
- harness-delegate-ng/templates/upgrader/upgraderJob.yaml
- harness-delegate-ng/templates/upgrader/upgraderRole.yaml
- harness-delegate-ng/templates/upgrader/upgraderRoleBinding.yaml
- harness-delegate-ng/templates/upgrader/upgraderSecret.yaml
- harness-delegate-ng/templates/upgrader/upgraderServiceAccount.yaml
- harness-delegate-ng/values.yaml
- index.yaml
1 - Copied internal harness-delegate-ng helm chart here. 
2- Added contributor license as part of previous commit.
3- modified index.yaml and only copied fields only related to harness-delegate-ng 
4- branch protection is added to main, push is disabled without an approval from member of harness-app. 
related secops ticket for ref: https://harness.atlassian.net/browse/SECOPS-4403 
Testing:
delegate works fine when installed using local repo, will test in QA env after merging of pr.
> OpenSource delegate helm chart: Add delegate chart for NG

- harness-delegate-ng/Chart.yaml
- harness-delegate-ng/values.yaml
- index.yaml
JIRA: https://harness.atlassian.net/browse/DEL-5379
Testing:
Tested with low configuration 512, 768 and 1024MB memory. With 512, 768 OOM is thrown, with 1024 delegates comes up and goes down soon after startup. Delegate works fine with 2GB of memory, increase default liveness probe to avoid frequent restarts. This variable is configurable anyways via delegate-values.yaml
> Increase liveness probe for helm delegate

- harness-delegate-ng/templates/secret.yaml
As part of https://github.com/harness/harness-core/pull/42545, Token copied is already base64 encoded.
Verified with helm dry run and checked the output.
> fix: [DEL-5758]: The token copied from ng UI will be already base64 encoded

- harness-delegate-ng/templates/secret.yaml
Reverts harness/delegate-helm-chart#12
Description:
With the newly discussed release plan, documented here https://harness.atlassian.net/wiki/spaces/DEL/pages/21296022393/Release+strategy+for+Install+UI+Base64+token+changes
We will take approach two, in which Helm chart will have no change. 
Test:
We have verified all the combinations in pre-QA and PR, the test results are in https://harness.atlassian.net/wiki/spaces/DEL/pages/21291469166/Base64+Token+changes+Validation+Details
> Revert "fix: [DEL-5758]: The token copied from ng UI will be already base64 encoded"

- harness-delegate-ng/templates/configMap.yaml
- harness-delegate-ng/values.yaml
Testing:
- Bought up a delegate in CG, by setting nextGen = false using this chart and executed shell script task.
- Bought up a delegate in NG with default nextGen value which is true
> Enable ng chart for immuutable delegate in cg

- .editorconfig
- harness-delegate-ng/Chart.yaml
- harness-delegate-ng/templates/_helpers.tpl
- harness-delegate-ng/templates/deployment.yaml
- harness-delegate-ng/templates/shared_certificates/certificateConfigMap.yaml
- harness-delegate-ng/templates/shared_certificates/certificateSecret.yaml
- harness-delegate-ng/values.yaml
Added support to include a mounted shared certificate trust chain
Added support for Custom Envs, VolumeMounts, and Volumes
Documentation detailing process to include custom shared certificate trust chains:
https://developer.harness.io/docs/continuous-integration/use-ci/set-up-build-infrastructure/configure-a-kubernetes-build-farm-to-use-self-signed-certificates/
> Add Support for Custom Shared Certificates, Custom Envs, Custom VolumeMounts, and Custom Volumes

- harness-delegate-ng/templates/deployment.yaml
- harness-delegate-ng/values.yaml
Set minimum number of seconds for which a newly created Pod should be ready without any of its containers crashing, for it to be considered available.
This is set for improving stability during upgrade. It will tell kubernetes to wait at least this amount of seconds before removing the old pod after the new one becomes ready.
Test:
Test required for this PR is same as https://github.com/harness/harness-core/pull/47039
> fix: [PL-38283]: increase wait time during rolling upgrade

- harness-delegate-ng/Chart.yaml
- harness-delegate-ng/README.md
reverting chart version to 1.0.9 from 1.0.10 because we longer manually update version in chart.yaml. 
Version in chart.yaml is updated by pipeline at the time of release. 
https://harness.atlassian.net/wiki/spaces/DEL/pages/21267447835/Publishing+Delegate+Helm+Chart+in+NG
> revert chart version to 1.0.9

- harness-delegate-ng/templates/configMap.yaml
- harness-delegate-ng/templates/deployment.yaml
- harness-delegate-ng/values.yaml
Changes:
1- Make accountID not mandatory so that customers can run helm template without accountId mentioned.
2- Correct envs -> env in deployment.yaml
3- Make deployMode configurable with default value KUBERNETES, this is done so that in on-prem system we can override it with KUBERNETES_ONPREM
Testing:
1- helm template doesn't throw error when accountId is not mentioned.
2- Installed helm delegate on ng smp test and it came up.
JIRA: 
https://harness.atlassian.net/browse/PL-38918 
https://harness.atlassian.net/browse/SMP-1368
https://harness.atlassian.net/browse/PL-38919
> Bug fixes in helm chart.

- harness-delegate-ng/templates/hpa.yaml
- harness-delegate-ng/values.yaml
Testing:
1- Tested delegate using hpa based on memory and cpu with max replica 2.
> Fix: [PL-39737]: Moving hpa version from v2/beta1 to v2

- harness-delegate-ng/values.yaml
This is required because we update this using pipeline at the chart release.
In script use in pipeline we search for empty dockerImage and then replace it with mentioned version. If dockerImage is not empty we will not be able to find it hence image will not be updated using pipeline.
Script snippet that we use
```
stringToModify='delegateDockerImage: '
repo='harness/delegate'
delegateImageTag=$repo:$DELEGATE_VERSION
versionString='version: '
actualString='delegateDockerImage: ""'
replacedString=$stringToModify$delegateImageTag
sed -i -e "s|${actualString}|${replacedString}|g" values.yaml
```
> making docker image as empty in values.yaml

- harness-delegate-ng/templates/hpaLegacy.yaml
- harness-delegate-ng/values.yaml
JIRA: https://harness.atlassian.net/browse/PL-39737
Making HPA backward compatible.
Testing:
1- minikube, k8 cluster version 1.22.16
Bought up delegate and checked.
2- pl-play cluster, k8 version 1.25.x
Bought up delegate and checked.
> [PL-39739]: hpa changes for backward compatibility

- harness-delegate-ng/templates/deployment.yaml
- harness-delegate-ng/values.yaml
Adding custom annotation support for delegate deployment
1- To add annotations from override yaml, add your annotation in override.yaml file and apply it.
Example:
annotations:
abc.io/propery: "true"
2- For adding annotation using command line refer below example:
--set annotations."prometheus\.io/path"="/api/metrics" \
--set-string annotations."prometheus\.io/scrape"=true 
Testing:
Installed delegate using.
1- Original delegate with no new changes and prometheus annotations.
2- Delegate with custom annotations using override.yaml 
3- Delegate with custom annotations using command line.
> feat: [PL-38515]: Adding custom annotation support for delegate deployment

- harness-delegate-ng/templates/ccm/cost-access.yaml
- harness-delegate-ng/values.yaml
Adding CCM visibility clusterrole to delegate helm chart.
Why? When new customers are setting up CCM for k8s they have to deploy a delegate first, and then add the cluster visibility role later. This is only given to you in the UI, which leads to issues when infra teams are tasked with rolling out the delegate over many clusters and do not want to go to the harness UI every time.
This gives the customers an easier onboarding flow for enrolling clusters into CCM.
Previous flow:
1. engineer deploys delegate into cluster via helm
2. engineer gets clusterrole yaml from harness owner
2. engineer adds clusterrole yaml into cluster via kubectl
New flow:
1. engineer deploys delegate into cluster via helm - adds ccm value to enable clusterrole
> Feat: [CCM-13259]: Add CCM Visibility Role

- harness-delegate-ng/templates/deployment.yaml
- harness-delegate-ng/values.yaml
JIRA: https://harness.atlassian.net/browse/PL-40553
1- We need to add delegateSecurityContext to set/override security context for delegate.
2- Need to stop using below to as access as non-root, instead new users should use delegateSecurityContext.
securityContext:
runAsRoot: false
3- For old users nothing will change, if they want to configure securityContext for delegate they shouldn't use deprecated field:
securityContext:
runAsRoot: false
Testing:
Bought up delegate with runAsRoot: true/false and delegateSecurityContext.
> feat: [PL-40553]: making security context configurable

- harness-delegate-ng/templates/_helpers.tpl
- harness-delegate-ng/templates/deployment.yaml
- harness-delegate-ng/templates/secret.yaml
- harness-delegate-ng/templates/upgrader/upgraderJob.yaml
- harness-delegate-ng/templates/upgrader/upgraderSecret.yaml
- harness-delegate-ng/values.yaml
Secrets are managed out of the helm chart lifecycle when secret management tools are in place. Therefore, the chart should bring the option to use existing secrets in the namespace.
> feat: use delegate token from existing secret

- harness-delegate-ng/templates/deployment.yaml
- harness-delegate-ng/values.yaml
- Add functionality to add dnsConfig and dnsPolicy to manifest using override file.
Testing:
- Tested using cloudflare DNS 1.1.1.1, disabled kube-dns using dnsPolicy as none Adding ss below
- Tested with default scenario, i.e without dnsConfig and dnsPolicy and delegate came up fine.
> Make dnsConfig configurable

- harness-delegate-ng/templates/configMap.yaml
- harness-delegate-ng/templates/deployment.yaml
- harness-delegate-ng/templates/upgrader/upgraderJob.yaml
- harness-delegate-ng/values.yaml
Changes:
- User will be able to add custom cert at fix path in delegate at:  /opt/harness-delegate/ca-bundle/ This path is fixed because we can only add alternate path in custom image and in custom image volume isn't required because certs are baked in. For this approach to work user must add secretName which contains custom certs.
- User will be able to add custom cert at fix path in upgrader at:  /ca-bundle . For this approach to work user must add secretName which contains custom certs
- Add support for DESTINATION_CA_PATH to use custom cert in CI pods, CI_MOUNT_VOLUMES are also supported same as https://developer.harness.io/docs/continuous-integration/use-ci/set-up-build-infrastructure/k8s-build-infrastructure/configure-a-kubernetes-build-farm-to-use-self-signed-certificates/
Testing: …
> feat: [PL-43413]: add support for custom cert in delegate and upgrader

- harness-delegate-ng/templates/hpa.yaml
closes #60 
```
➜  delegate-helm-chart git:(main) ✗ helm template --namespace harness-delegate-ng --create-namespace \
./harness-delegate-ng \
--set delegateName=helm-delegate \
--set accountId=wlgELJ0TTre5aZhzpt8gVA \
--set delegateToken=xxxxxx \
--set managerEndpoint=https://app.harness.io/gratis \
--set delegateDockerImage=harness/delegate:24.01.82202 \
--set replicas=1 --set upgrader.enabled=true --set autoscaling.enabled=true | grep 'autoscaling/v2' -A 24
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
name: helm-delegate
namespace: harness-delegate-ng
labels:
helm.sh/chart: harness-delegate-ng-1.0.14
app.kubernetes.io/managed-by: Helm
app.kubernetes.io/name: helm-delegate
app.kubernetes.io/instance: release-name
harness.io/name: helm-delegate
spec:
scaleTargetRef: …
```
> fix: GitVersion

- harness-delegate-ng/templates/deployment.yaml
I would like to add a named port to the delegate deployment for the api.
I am not sure what else this API is used for other than /health and /metrics, but I am using PodMonitor to define scrape targets, which requires a **named port** to collect metrics.
https://doc.crds.dev/github.com/prometheus-operator/kube-prometheus/monitoring.coreos.com/PodMonitor/v1@v0.7.0
I do not belive this needs to be further templated as the port is defined in the liveprobes. `prometheus.io/port: "3460"` is in the values but I am not sure if we should drive this port from that, I belive this port is part of the delegate itself and wouldnt be changed by the user.
> expose container port for api

- harness-delegate-ng/templates/upgrader/upgraderJob.yaml
- harness-delegate-ng/values.yaml
A customer has strict cluster security policies, one of which requires a specific security context on all containers.
We need to expose the security context for them so they can pass their security checks.
> feat: set security context for upgrader

- harness-delegate-ng/templates/deployment.yaml
Otherwise CI tools will always detect a change if replicas != current replicas of the hpa.
And also it will force that number on apply, even if the service is scaled.
> Ignore replicas when HPA is enabled

- harness-delegate-ng/templates/hpaLegacy.yaml
I updated this in hpa, missed fixing it in legacy.
https://github.com/harness/delegate-helm-chart/pull/78
> Update hpaLegacy.yaml GitVersion

- harness-delegate-ng/templates/deployment.yaml
- harness-delegate-ng/values.yaml
adds support for injecting init containers and sidecar containers into the deployment spec of the delegate.
> add support for custom_init_containers & custom_containers in delegate deployment template

- harness-delegate-ng/templates/_helpers.tpl
- harness-delegate-ng/templates/ccm/cost-access.yaml
- harness-delegate-ng/templates/cluster-rolebinding.yaml
- harness-delegate-ng/templates/configMap.yaml
- harness-delegate-ng/templates/customRoleBinding.yaml
- harness-delegate-ng/templates/deployment.yaml
- harness-delegate-ng/templates/hpa.yaml
- harness-delegate-ng/templates/hpaLegacy.yaml
- harness-delegate-ng/templates/proxy/proxyConfigMap.yaml
- harness-delegate-ng/templates/proxy/proxySecret.yaml
- harness-delegate-ng/templates/role.yaml
- harness-delegate-ng/templates/roleBinding.yaml
- harness-delegate-ng/templates/secret.yaml
- harness-delegate-ng/templates/serviceaccount.yaml
- harness-delegate-ng/templates/shared_certificates/certificateConfigMap.yaml
- harness-delegate-ng/templates/shared_certificates/certificateSecret.yaml
- harness-delegate-ng/templates/upgrader/upgraderConfigMap.yaml
- harness-delegate-ng/templates/upgrader/upgraderJob.yaml
- harness-delegate-ng/templates/upgrader/upgraderRole.yaml
- harness-delegate-ng/templates/upgrader/upgraderRoleBinding.yaml
- harness-delegate-ng/templates/upgrader/upgraderSecret.yaml
- harness-delegate-ng/templates/upgrader/upgraderServiceAccount.yaml
- harness-delegate-ng/values.yaml
This PR adds support to add additional labels and annotations to all resources at three different levels.
```
commonAnnotations: {}
commonLabels: {}
delegateLabels: {}
delegateAnnotations: {}
annotations: {}.  # Already present
delegatePodLabels: {}
```
I have tested these scenarios for all resources
1. should work with common annotations
2. should work with common labels
3. should work with common annotations and labels
4. should template without override
And these scenarios for deployment
1. should work with delegate annotations
2. should work with pod annotations
3. should work with common and delegate annotations
4. should work with common and pod annotations
5. should work with delegate and pod annotations
6. should work with common, delegate and pod annotations
7. should work with …
> feat: [PL-57609]: Support to add labels and annotations in deployment and pod spec

- harness-delegate-ng/templates/upgrader/upgraderConfigMap.yaml
- harness-delegate-ng/values.yaml
Add option to specify upgrader registry mirror during helm installation. 
Generated Helm templates locally and made sure expected config is generated:
```
helm template ./harness-delegate-ng # No mirror configured
helm template ./harness-delegate-ng --set upgrader.registryMirror="https://us.gcr.io/harness/delegate/"
helm template ./harness-delegate-ng --set upgrader.registryMirror="us.gcr.io/harness"
```
> feat: [PL-58735]: Add registry mirror helm option for upgrader

- harness-delegate-ng/templates/configMap.yaml
- harness-delegate-ng/templates/deployment.yaml
- harness-delegate-ng/templates/upgrader/upgraderConfigMap.yaml
- harness-delegate-ng/templates/upgrader/upgraderJob.yaml
- harness-delegate-ng/values.yaml
Currently, there is no configuration available to enable mTLS on the delegate when installed using the Helm command. To support mTLS, specific environment variables, volumes, and volume mounts must be included in the generated Helm template.
After this change, it is required to provide a secret name in the Helm install command. This secret should contain the TLS certificate and private key. Some changes are still needs to be done at the backend side for updating the manager URL.
FR: https://developer.harness.io/docs/platform/delegates/secure-delegates/delegate-mtls-support/
> fix: [PL-59074]: adds mTLS config in deployment, upgraderConfigMap and upgraderJob

- harness-delegate-ng/templates/deployment.yaml
- harness-delegate-ng/values.yaml
This Solves the GitHub Issue #117 
✅ Addresses the core problem: Users can now customize maxSurge and maxUnavailable parameters to prevent rollout failures with HPA and low replica counts
✅ Backward compatible: Existing deployments will continue working with the same behavior (defaults to 1/1)
✅ Flexible configuration: Users can now set custom values in their values.yaml:
yaml
✅ Safe implementation: Only applies to RollingUpdate strategy, preventing errors with Recreate strategy
**How to test**
```
helm template test-release ./harness-delegate-ng --set accountId=test123 --set delegateToken=testtoken123 --set "rollingUpdate.maxSurge=2,rollingUpdate.maxUnavailable=25%" | grep -A 10 "strategy:"
```
**Expected Output**
```
strategy:
type: RollingUpdate
rollingUpdate:
maxSurge: 2 …
```
> feat: Added support for customizing rollingUpdate strategy

- harness-delegate-ng/templates/upgrader/upgraderJob.yaml
- harness-delegate-ng/values.yaml
Added upgrader schedule as a configurable parameter with default value "0 */1 * * *"
- Installed a delegate successfully with and without `upgrader.schedule` configuration 
- Install command with `upgrader.schedule` configuration 
```
helm upgrade -i soumik-helm-delegate --namespace harness-delegate-ng --create-namespace . \
--set delegateName=soumik-helm-delegate \
--set accountId=n1yjV_FdQ9GBlBkidw \
--set delegateToken=MGI1MjkzMzQzNjNTMzNzdhMThlZDY= \
--set managerEndpoint=https://app.harness.io \
--set delegateDockerImage=us-docker.pkg.dev/gar-prod-setup/harness-public/harness/delegate:25.08.86503 \
--set replicas=1 \
--set upgrader.enabled=true --set upgrader.schedule="* * * * *"
```
> feat: [PL-63080]: Add schedule option to upgrader helm options
